pipeline {
    agent any
        tools {
        maven 'maven' // Name used in Global Tool Configuration
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building order-service...'
                sh 'mvn clean package'
            }
        }

        stage('Docker Build & Push') {
            steps {
                echo 'Building Docker Image'
                sh 'docker build -t jithu145/order-service .'
                withCredentials([usernamePassword(credentialsId: 'fb16b1ba-d2e9-41bb-8654-d00d3b5b61e6', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                    sh 'docker push jithu145/order-service'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploying...'
                sh 'kubectl apply -f k8s/order-deployment.yaml'
            }
        }
    }
}
