pipeline {
    agent any
        tools {
        maven 'maven' // Name used in Global Tool Configuration
    }

    stages {
stage('Build') {
    steps {
        echo 'Building user-service...'
        dir('user-service') {
            sh 'mvn clean package'
        }
    }
}



        stage('Docker Build & Push') {
            steps {
                echo 'Building Docker Image'
                dir('user-service') {
                sh 'docker build -t kpkm25/user-service .'
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                    sh 'docker push kpkm25/user-service'
                }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploying...'
                sh 'kubectl apply -f k8s/user-deployment.yaml'
            }
        }
    }
}
